# k8s service nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8800
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx